/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "ChBlog",
  "tagline": "welcom to my blog",
  "favicon": "img/logo.ico",
  "url": "https://blog.chdl.fun",
  "baseUrl": "/ChBlog/en/",
  "projectName": "blog",
  "organizationName": "cuihaoweb",
  "deploymentBranch": "rb",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "zh",
    "locales": [
      "en",
      "zh"
    ],
    "localeConfigs": {
      "en": {
        "htmlLang": "en",
        "direction": "ltr"
      },
      "zh": {
        "htmlLang": "zh",
        "direction": "ltr"
      }
    },
    "path": "i18n"
  },
  "headTags": [
    {
      "tagName": "script",
      "attributes": {
        "type": "text/javascript"
      },
      "innerHTML": "\n                var _hmt = _hmt || [];\n                (function() {\n                    var hm = document.createElement(\"script\");\n                    hm.src = \"https://hm.baidu.com/hm.js?9f42b9e0421867461c737dfa74f0e34d\";\n                    var s = document.getElementsByTagName(\"script\")[0]; \n                    s.parentNode.insertBefore(hm, s);\n                })();\n            "
    }
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "editUrl": "https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/"
        },
        "blog": {
          "showReadingTime": true,
          "sortPosts": "descending",
          "editUrl": "https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themes": [
    [
      "@easyops-cn/docusaurus-search-local",
      {
        "hashed": true
      }
    ]
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "metadata": [
      {
        "name": "keywords",
        "content": "ch,blog"
      },
      {
        "name": "description",
        "content": "the blog of ch, it has some articles about web, welcome to visit"
      },
      {
        "name": "google-site-verification",
        "content": "fs5EybByxqvIchWyU4mIpxHS8HJrFYX8flIiBwdT6ps"
      },
      {
        "name": "baidu-site-verification",
        "content": "codeva-8tsunVRxb2"
      }
    ],
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "navbar": {
      "title": "ChBlog",
      "logo": {
        "alt": "Ch Blog Logo",
        "src": "img/logo.png"
      },
      "items": [
        {
          "to": "/docs/intro",
          "label": "教程",
          "position": "right",
          "items": [
            {
              "to": "/docs/category/nextjs",
              "label": "NextJs全栈指南"
            }
          ]
        },
        {
          "to": "/blog",
          "label": "Blog",
          "position": "right"
        },
        {
          "href": "https://qm.qq.com/cgi-bin/qm/qr?authKey=wmRMf3Lvbja6pVb9bo408uo2rYLXoZ%2F4PHryjyWxEOAQfsqF%2Bwes%2B%2B0FSKGYvxz%2B&k=3scUvuyQgGHT7CMr2QI_F9G7DUT6r6CS&noverify=0#",
          "label": "QQ群",
          "position": "right",
          "hover": "https://jmy-pic.baidu.com/0/pic/-1802197421_-403708105_-381229119.png",
          "className": "qq-nav-item"
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Tutorial",
              "to": "/"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Blog",
              "to": "/blog"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/cuihaoweb"
            }
          ]
        },
        {
          "title": "Links",
          "items": [
            {
              "label": "ch home",
              "to": "https://www.chdl.fun"
            },
            {
              "label": "toolkit",
              "href": "https://tk.chdl.fun"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2024 My Project."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "code-block-error-line",
          "line": "error-line"
        },
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ],
      "additionalLanguages": []
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "scripts": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    }
  }
};
