name: Build and Deploy
on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache-dir
        shell: bash
        run: echo "dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        id: pnpm-cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install
        run: |
          pnpm i --no-frozen-lockfile

      - name: Build
        run: |
          npm run build

      - name: Clean node_modules
        run: |
          rm -rf .gitignore
          mv script/.gitignore.template .gitignore
          shopt -s extglob
          rm -rf !(build|script)

      - name: Deploy rb branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: rb

  sync-to-gitee:
    concurrency: ci-${{ github.ref }}
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_DEPLOY_KEY }}
        with:
          source-repo: "git@github.com:cuihaoweb/blog.git"
          destination-repo: "git@gitee.com:cui_hao/blog.git"
